### PR TITLE
KernelSU compatibility

### PR DESCRIPTION
**Pull request by amteza**
Executing zipsigner with su -c to fix this script under KernelSU

### CODE REVIEW

**Comment by amteza** [comment]
@F3FFO, review this; it fixed installation with the latest KernelSU Manager. I run it in a Google Pixel 7 Pro (Android 14). The only additional thing was selecting Vanadium in Developer Options and disabling Android Webview manually, just in case.

**Comment by F3FFO** [comment]
> Executing zipsigner with su -c to fix this script under KernelSU

Thanks for your contribution.

May I ask you how you came up with this solution?

**Comment by F3FFO** [comment]
> @F3FFO, review this; it fixed installation with the latest KernelSU Manager. I run it in a Google Pixel 7 Pro (Android 14). The only additional thing was selecting Vanadium in Developer Options and disabling Android Webview manually, just in case.

In the next release I will try to fix it

**Comment by amteza** [comment]
@F3FFO, answering your question, I just observed that when running zipsigner it failed due to lack of root/su permissions. By default in KernelSU unless the tool is part of ash (KernelSU's shell) it will be executed without root. KernelSU works whitelisting the apps than can use root. So, a quick fix is just calling zipsigner explicitly with the su -c command. You must enable in KernelSU com.android.shell to have access to root too, maybe good to call this out as part of the instructions for KernelSU user like myself. BTW, _grazie mile_ for this module.

**Pull request merged**
