### PR TITLE
Switch to AAPT2

### LINKED ISSUE #39: Setup failed since latest Google patch (June)
[magisk_install_log_2024-06-12T20.24.58.log](https://github.com/user-attachments/files/15809425/magisk_install_log_2024-06-12T20.24.58.log)
```
!!! Overlay creation has failed !!!
Compatibility is unlikely, please report this to your ROM developer.
Some ROMs need a patch to fix this.
Do NOT report this issue to me.

Aborting...
! Installation failed
```

Stock Android 14
Google Pixel 7
Magisk 27.0

I DID report this to you, since Google won't change or do anything about it and the only chance for it to start working again would be YOU helping me to find a fix.

And, most importantly, your module has always been the only working way to install a custom webview on my phone.

### PR DESCRIPTION
**Pull request by XRevan86**
Fixes #39.

### CODE REVIEW

**Comment by F3FFO** [comment]
I really appreciate your contribution, I will test your changes and if they go well I will merge it

**Comment by F3FFO** [comment]
Where the aapt2 binaries come from?

**Comment by F3FFO** [comment]
Anyway I tested your changes and everything seems to work correctly, so I'll wait for your feedback on the source of the binary files and then I'll proceed to merge

**Comment by XRevan86** [comment]
> Where the aapt2 binaries come from?

From [QuickSwitch](https://github.com/j7b3y/QuickSwitch), as it has the smallest binaries, other candidates were [https://github.com/lzhiyong/android-sdk-tools](lzhiyong/android-sdk-tools), [https://github.com/JonForShort/android-tools](JonForShort/android-tools), [https://github.com/AndroidIDEOfficial/platform-tools](AndroidIDEOfficial/platform-tools).

**Pull request merged**
